package Level1;

public enum Ingredients {
    FLOUR,YEAST,WATER,OIL,SALT,SUGAR,CORNMEAL,HERBS,MOZZARELLA, TOMATO,
    PEPPERONI, PEPPER, ONION, MUSHROOM, SAUSAGE, BASIL, PINEAPPLE, OLIVES,
    GORGONZOLA,PARMESAN, FONTINA
}
